version: '3'


services:

  nutritious-food:
    image: nutritious-food:latest
    container_name: nutritious-food-server
    ports:
      - 9000:9000
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge